### ISSUE TITLE
Dependency Track authentication error

### ISSUE THREAD

**Issue by ascheid** [cds-snc/security-tools#83]
The [PR](https://github.com/cds-snc/security-tools/pull/75) changes were made and password rotation was triggered. That caused dependency track to fail authentication to its database.

**Comment by patheard** [comment]
I have a suspicion that it's related to the special characters that got generated in our latest password and how they behave when exported into an environment variable:
https://github.com/cds-snc/security-tools/blob/main/terragrunt/aws/software_asset_inventory/ssm.tf#L7

**Comment by patheard** [comment]
Underlying problem has been found:

- Database cluster password updates are only applied during the database maintenance window.
- The `terraform apply` updates the proxy connection string immediately with the new password, but the database still has the old password until the maintenance window.  As a result, the RDS proxy is no longer able to connect to the database.

The fix was to set database upgrades to apply immediately in #89.

**Comment by patheard** [comment]
@ascheid as a last task on this, can you please revert all our database connection test tomfoolery.   The two main commits to revert are to re-add all the special chars to the password:
- #84

And to go back to providing the username/password as environment variables:
- #85

**Comment by patheard** [comment]
This has now been fixed 🎉
